version: 2

workflows:
  version: 2
  test:
    jobs:
      - lint
      - unit

jobs:
  lint:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/previousnext/k8s-aws-efs
    steps:
      - checkout
      - run: |
          go get golang.org/x/lint/golint
          make lint

  unit:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/previousnext/k8s-aws-efs
    steps:
      - checkout
      - run: make test
